version: '3.5'

networks:
  base:
    name: base

services:
  slyph:
    build:
      context: .
    image: slyph
    container_name: slyph
    environment:
      APP_PORT: 8888
    ports:
      - 8888:8888
    depends_on:
      - db
    networks:
      - base      
  db:
    build:
      context: ./db
    image: slyph-db
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    networks:
      - base
