package routers

import (
	"github.com/astaxie/beego"
	"Slyph/controllers"
)

// @APIVersion 1.0.0
// @Title Slyph 基于Docker的应用负载均衡优化API
// @Description 接口包含POD,Service,Deployment的创建删除和查看
// @Contact haoyun@ghostcloud.cn
// @TermsOfServiceUrl haoyun@ghostcloud.cn
// @License Apache 2.0
// @LicenseUrl http://www.apache.org/licenses/LICENSE-2.0.html
func init() {
	ns := beego.NewNamespace("/v1",
		beego.NSNamespace("/getlog",
			beego.NSInclude(
				&controllers.LogController{},
			),
		),
		beego.NSNamespace("/index",
			beego.NSInclude(
				&controllers.IndexController{},
			),
			// beego.NSRouter("/index",
			// 	&controllers.IndexController{},
			// 	"get:Get"),
		),
		beego.NSNamespace("/user",
			beego.NSInclude(
				&controllers.LoginController{},
			),
			// beego.NSRouter("/login",
			// 	&controllers.LoginController{},
			// 	"get:Get"),
			// beego.NSRouter("/login",
			// 	&controllers.LoginController{},
			// 	"post:Post"),
		),
		beego.NSNamespace("/auto",
			beego.NSInclude(
				&controllers.AutoBuildController{},
				&controllers.AutoDownController{},
			),
			// beego.NSRouter("/up",
			// 	&controllers.AutoBuildController{},
			// 	"post:Post"),
			// beego.NSRouter("/down",
			// 	&controllers.AutoDownController{},
			// 	"post:Post"),
			// beego.NSRouter("/up",
			// 	&controllers.AutoBuildController{},
			// 	"get:Get"),
			// beego.NSRouter("/down",
			// 	&controllers.AutoDownController{},
			// 	"get:Get"),
		),
		beego.NSNamespace("/pod",
			beego.NSInclude(
				&controllers.GetPod{},
				&controllers.CreatePod{},
				&controllers.DeletePod{},
			),
			// beego.NSRouter("/getjson",
			// 	&controllers.GetPod{},
			// 	"get:Getjson"),
			// beego.NSRouter("/getinfo",
			// 	&controllers.GetPod{},
			// 	"get:Get"),
			// beego.NSRouter("/create",
			// 	&controllers.CreatePod{},
			// 	"get:Get"),
			// beego.NSRouter("/create",
			// 	&controllers.CreatePod{},
			// 	"post:Post"),
			// beego.NSRouter("/delete",
			// 	&controllers.DeletePod{},
			// 	"get:Get"),
			// beego.NSRouter("/delete",
			// 	&controllers.DeletePod{},
			// 	"post:Post"),
		),
		beego.NSNamespace("/service",
			beego.NSInclude(
				&controllers.GetService{},
				&controllers.CreateService{},
				&controllers.DeleteService{},
			),
			// beego.NSRouter("/getjson",
			// 	&controllers.GetService{},
			// 	"get:Getjson"),
			// beego.NSRouter("/getinfo",
			// 	&controllers.GetService{},
			// 	"get:Get"),
			// beego.NSRouter("/create",
			// 	&controllers.CreateService{},
			// 	"get:Get"),
			// beego.NSRouter("/create",
			// 	&controllers.CreateService{},
			// 	"post:Post"),
			// beego.NSRouter("/delete",
			// 	&controllers.DeleteService{},
			// 	"get:Get"),
			// beego.NSRouter("/delete",
			// 	&controllers.DeleteService{},
			// 	"post:Post"),
		),
		beego.NSNamespace("/st",
			beego.NSInclude(
				&controllers.GetStatefulset{},
				&controllers.CreateStatefulset{},
				&controllers.DeleteStatefulset{},
			),
		),
		beego.NSNamespace("/sto",
			beego.NSInclude(
				&controllers.GetStorage{},
				&controllers.AddStorage{},
				&controllers.DeleteStorage{},
			),
		),
		beego.NSNamespace("/deployment",
			beego.NSInclude(
				&controllers.GetDeployment{},
				&controllers.CreateDeployment{},
				&controllers.DeleteDeployment{},
				&controllers.UpdateDeployment{},
				&controllers.RollBackDeployment{},
			),
			// beego.NSRouter("/getjson",
			// 	&controllers.GetDeployment{},
			// 	"get:Getjson"),
			// beego.NSRouter("/getinfo",
			// 	&controllers.GetDeployment{},
			// 	"get:Get"),
			// beego.NSRouter("/create",
			// 	&controllers.CreateDeployment{},
			// 	"get:Get"),
			// beego.NSRouter("/create",
			// 	&controllers.CreateDeployment{},
			// 	"post:Post"),
			// beego.NSRouter("/delete",
			// 	&controllers.DeleteDeployment{},
			// 	"get:Get"),
			// beego.NSRouter("/delete",
			// 	&controllers.DeleteDeployment{},
			// 	"post:Post"),
			// beego.NSRouter("/update",
			// 	&controllers.UpdateDeployment{},
			// 	"post:Post"),
		),
	)
	beego.AddNamespace(ns)
}
